version: 2

jobs:

  shellcheck:
    working_directory: /work
    docker: [{image: 'docker:17.06-git'}]
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
      - run:
          name: "Run shellcheck"
          command: |
            dockerfile=.ci/dockerfiles/Dockerfile.shellcheck
            echo "COPY . ." >> $dockerfile
            docker build -f $dockerfile --tag cli-validator:$CIRCLE_BUILD_NUM .
            docker run --rm \
                cli-validator:$CIRCLE_BUILD_NUM \
                make shellcheck

workflows:
  version: 2
  ci:
    jobs:
      - shellcheck
