VAGRANT_API_VERSION = '2'
Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.define "docker-try.vbox" do |_|
    _.vm.box = "ubuntu/xenial64"
    _.vm.network :forwarded_port, guest: 9000, host: 9000
    _.vm.provider "virtualbox" do |__|
      __.name = "docker-try.doe.cloud"
      __.memory = "1024"
      __.cpus = "1"
    end

    _.vm.provision "docker" do |d| 
      d.run "portainer", image: "portainer/portainer", args: "-p 9000:9000 -v '/var/run/docker.sock:/var/run/docker.sock'"
    end


  end
end
